spring:
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/fraud
    password:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: Fraud
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
